class EarningModel {
  String? name,
      owner,
      creation,
      modified,
      modifiedBy,
      parent,
      parentField,
      parentType,
      salaryComponent,
      doctype,
      abbr;
  int? statisticalComponent,
      dependsOnPaymentDays,
      exemptedFromIncomeTax,
      isTaxApplicable,
      isFlexibleBenefit,
      variableBasedOnTaxableSalary,
      doNotIncludeInTotal,
      deductFullTaxOnSelectedPayrollDate,
      amountBasedOnFormula,
      idx,
      docStatus,
      isRecurringAdditionalSalary;

  double? amount,
      yearToDate,
      defaultAmount,
      additionalAmount,
      taxOnFlexibleBenefit,
      taxOnAdditionalSalary;

  EarningModel({
    this.name,
    this.owner,
    this.creation,
    this.modified,
    this.modifiedBy,
    this.parent,
    this.parentField,
    this.parentType,
    this.salaryComponent,
    this.doctype,
    this.abbr,
    this.statisticalComponent,
    this.dependsOnPaymentDays,
    this.exemptedFromIncomeTax,
    this.isTaxApplicable,
    this.isFlexibleBenefit,
    this.variableBasedOnTaxableSalary,
    this.doNotIncludeInTotal,
    this.deductFullTaxOnSelectedPayrollDate,
    this.amountBasedOnFormula,
    this.idx,
    this.docStatus,
    this.isRecurringAdditionalSalary,
    this.amount,
    this.yearToDate,
    this.defaultAmount,
    this.additionalAmount,
    this.taxOnFlexibleBenefit,
    this.taxOnAdditionalSalary,
  });

  factory EarningModel.formJson(Map<String, dynamic> json) => EarningModel(
        name: json['name'],
        owner: json['owner'],
        creation: json['creation'],
        modified: json['modified'],
        modifiedBy: json['modified_by'],
        parent: json['parent'],
        parentField: json['parentfield'],
        parentType: json['parenttype'],
        salaryComponent: json['salary_component'],
        doctype: json['doctype'],
        abbr: json['abbr'],
        statisticalComponent: json['statistical_component'],
        dependsOnPaymentDays: json['depends_on_payment_days'],
        exemptedFromIncomeTax: json['exempted_from_income_tax'],
        isTaxApplicable: json['is_tax_applicable'],
        isFlexibleBenefit: json['is_flexible_benefit'],
        variableBasedOnTaxableSalary: json['variable_based_on_taxable_salary'],
        doNotIncludeInTotal: json['do_not_include_in_total'],
        deductFullTaxOnSelectedPayrollDate:
            json['deduct_full_tax_on_selected_payroll_date'],
        amountBasedOnFormula: json['amount_based_on_formula'],
        idx: json['idx'],
        docStatus: json['docstatus'],
        isRecurringAdditionalSalary: json['is_recurring_additional_salary'],
        amount: json['amount'],
        yearToDate: json['year_to_date'],
        defaultAmount: json['default_amount'],
        additionalAmount: json['additional_amount'],
        taxOnFlexibleBenefit: json['tax_on_flexible_benefit'],
        taxOnAdditionalSalary: json['tax_on_additional_salary'],
      );
}
